name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/blueshirt.png
    - assets/images/yournamehoodie.png
    - assets/images/pizza.png
    - assets/images/flat.png
    - assets/images/pink.png
    - assets/images/pink_tshirt.png
    - assets/images/shoodie.png
    - assets/images/sshirt.png
    - assets/images/postcard.png
    - assets/images/bookmark.png
    - assets/images/notebook.png
    - assets/images/printshack.png
    - assets/images/classichoodie.png
    - assets/images/classicsweatshirt.png
    - assets/images/classictshirt.png
    - assets/images/graduationhoodie.jpg
    - assets/images/threeziphoodie.jpg
    - assets/images/classiccap.png
    - assets/images/classicbeaniehat.png
    - assets/images/rainbowhoodie.png
    - assets/images/graduationtie.png
    - assets/images/graduationnotebook.png
    - assets/images/graduationbadge.png
    - assets/images/graduationponcho.png
    - assets/images/graduationbag.png
    - assets/images/pumpkintote.png
    - assets/images/bootote.png
    - assets/images/ghosttote.png
    - assets/images/graduationbear.png
    - assets/images/idholder.png
    - assets/images/lanyard.png
    - assets/images/cottonshopper.png
    - assets/images/rainbowlanyard.png
    - assets/images/lapelpin.png
    - assets/images/keyring.png
    - assets/images/coaster.png
    - assets/images/waterbottle.png
    - assets/images/pridepin.png
    - assets/images/pridebracelet.png


    

